- name: Check if /etc/bash.bashrc is present (ubuntu/debian)
  ansible.builtin.stat:
    path: "/etc/bash.bashrc"
  register: file_stat_bash_bashrc

- name: Enable micromamba in bash (ubuntu/debian)
  ansible.builtin.lineinfile:
    path: "/etc/bash.bashrc"
    regexp: '^eval "\$\({{ dest }} shell hook --shell=bash\)"$'
    line: eval "$({{ dest }} shell hook --shell=bash)"
    insertafter: EOF
    state: present
  when: file_stat_bash_bashrc.stat.exists and file_stat_bash_bashrc.stat.isreg

- name: Replace old micromamba line if present (ubuntu/debian)
  ansible.builtin.lineinfile:
    path: "/etc/bashrc"
    regexp: '^eval "\$\(micromamba shell hook --shell=bash\)"$'
    state: absent
  when: file_stat_bash_bashrc.stat.exists and file_stat_bash_bashrc.stat.isreg


- name: Check if /etc/bashrc is present (redhat-like)
  ansible.builtin.stat:
    path: "/etc/bashrc"
  register: file_stat_bashrc

- name: Enable micromamba in bash (redhat-like)
  ansible.builtin.lineinfile:
    path: "/etc/bashrc"
    regexp: '^eval "\$\({{ dest }} shell hook --shell=bash\)"$'
    line: eval "$({{ dest }} shell hook --shell=bash)"
    insertafter: EOF
    state: present
  when: file_stat_bashrc.stat.exists and file_stat_bashrc.stat.isreg

- name: Replace old micromamba line if present (redhat-like)
  ansible.builtin.lineinfile:
    path: "/etc/bashrc"
    regexp: '^eval "\$\(micromamba shell hook --shell=bash\)"$'
    state: absent
  when: file_stat_bashrc.stat.exists and file_stat_bashrc.stat.isreg


- name: Check if zshrc is present
  ansible.builtin.stat:
    path: "/etc/zsh/zshrc"
  register: file_stat_zshrc

- name: Enable micromamba in zsh if present
  ansible.builtin.lineinfile:
    path: "/etc/zsh/zshrc"
    regexp: '^eval "\$\({{ dest }} shell hook --shell=zsh\)"$'
    line: eval "$({{ dest }} shell hook --shell=zsh)"
    insertafter: EOF
    state: present
  when: file_stat_zshrc.stat.exists and file_stat_zshrc.stat.isreg

- name: Replace old micromamba line if present (zsh)
  ansible.builtin.lineinfile:
    path: "/etc/zsh/zshrc"
    regexp: '^eval "\$\(micromamba shell hook --shell=zsh\)"$'
    state: absent
  when: file_stat_zshrc.stat.exists and file_stat_zshrc.stat.isreg
